apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-k8s-lab
  namespace: flask-k8s-lab
  labels:
    app.kubernetes.io/name: flask-k8s-lab
spec:
  ingressClassName: nginx
  rules:
    - host: flask-k8s-lab.example.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flask-k8s-lab
                port:
                  name: http
