apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - prune-probe.yaml

images:
  - name: registry.example.com/devops/flask-k8s-lab
    newName: registry.gitlab.com/goozcena-gnl/test-lab
    digest: sha256:0c14d7a7ddbb0641b7dfaf78fbaff8ae528dae53b1c7d1f91c9884a5a1469bd4

patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: flask-k8s-lab
      namespace: flask-k8s-lab
