apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../minikube

images:
  - name: registry.gitlab.com/goozcena-gnl/test-lab
    newName: flask-k8s-lab
    newTag: local

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: flask-k8s-lab
      namespace: flask-k8s-lab
    patch: |-
      - op: remove
        path: /spec/template/spec/imagePullSecrets

