apiVersion: v1
kind: Secret
metadata:
  name: flask-k8s-lab-repository
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: <GIT_REPOSITORY_URL>
  username: <GIT_USERNAME>
  password: <PROJECT_ACCESS_TOKEN>
