controller:
  ingressClassResource:
    name: nginx
    enabled: true
    default: false
    controllerValue: k8s.io/ingress-nginx
  ingressClass: nginx
  watchIngressWithoutClass: false
  service:
    type: LoadBalancer
