deployment:
  replicas: 1

ingressClass:
  enabled: true
  isDefaultClass: false
  name: traefik

providers:
  kubernetesIngress:
    enabled: true

    ingressEndpoint:
      hostname: flask-k8s-lab.localhost

    publishedService:
      enabled: false

  kubernetesCRD:
    enabled: false

  kubernetesGateway:
    enabled: false

gateway:
  enabled: false

service:
  spec:
    type: ClusterIP

api:
  dashboard: false

logs:
  general:
    level: INFO
  access:
    enabled: true

metrics:
  prometheus: null
